trainer:
  _target_: nlp_app_samples.model.Trainer
  optimizer:
    _target_: nlp_app_samples.optimizer.Optimizer
    algo: SGD
    lr: 0.01
  dataset:
    _target_: nlp_app_samples.model.Dataset
    name: Imagenet
    path: /datasets/imagenet